<?php
return array (
  'autogenerated-8-c9f0f895fb98ab9159f51fd0297e236d' => 
  array (
    'base' => 'http://cms24.s2310456026.student.kwmhgb.at/autogenerated-8',
    'errorHandling' => 
    array (
    ),
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'locale' => 'en_US.UTF-8',
        'navigationTitle' => 'English',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 8,
    'routes' => 
    array (
    ),
  ),
  'main' => 
  array (
    'base' => 'http://cms24.s2310456026.student.kwmhgb.at/',
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'Deutsch',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'locale' => 'de_DE',
        'navigationTitle' => 'DE',
        'flag' => 'at',
        'hreflang' => '',
        'websiteTitle' => '',
      ),
      1 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'locale' => 'en_US',
        'hreflang' => '',
        'base' => '/en/',
        'websiteTitle' => '',
        'navigationTitle' => 'EN',
        'fallbackType' => 'strict',
        'fallbacks' => '',
        'flag' => 'gb',
        'languageId' => 1,
      ),
    ),
    'rootPageId' => 1,
    'websiteTitle' => 'SPG Pregarten',
  ),
);
#